name: Deploy Azure infrastructure from Bicep

on:
  # ...

jobs:
  build-and-deploy:
    runs-on: # ...
    steps:

      # Checkout code
    - uses: # ...

      # Log into Azure
    - uses: # ...
      with:
        creds: # ...

      # Deploy Bicep file
    - name: # ...
      uses: # ...
      with:
        subscriptionId: # ...
        resourceGroupName: # ...
        template: # ...
        parameters: # ...
        failOnStdErr: false